### ISSUE TITLE
Blatant skid

### ISSUE THREAD

**Issue by OmenDoesStuff** [bl4stySKID/Trojan-AntiCheat#2]
Can’t even refactor. And closes my issue so people won’t see it lmaooooooooooo. Go learn java and don’t skid like this kid.

**Comment by OmenDoesStuff** [comment]
also love how your fucking reply is `Don't care + you fell off + didn't ask + ratio` I love how it proves how much of a loser you are to have to skid from a dead anticheat LMAO

**Comment by bl4stySKID** [comment]
You're even more of a loser to fall for a troll like this stay mad + ratio LOOOOL!
